apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- ./workflow-controller-rbac
- ./argo-server-rbac
- ./ingress.yaml

namespace: argo

images:
  - name: quay.io/argoproj/workflow-controller
    newTag: v3.3.4
  - name: quay.io/argoproj/argocli
    newTag: v3.3.4