apiVersion: v1
kind: Service
metadata:
  name: argo-server
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "config-default"}'
    cloud.google.com/app-protocols: '{"web":"HTTP"}'
spec:
  type: NodePort
  selector:
    app: argo-server
  ports:
    - name: web
      port: 2746
      targetPort: 2746
